export default function FaviconMeta() {
  return (
    <>
      <link rel="icon" type="image/x-icon" href="/favicon.ico" />
      <link
        rel="apple-touch-icon"
        sizes="57x57"
        type="image/png"
        href="/icons/apple-icon-57x57.png"
      />
      <link
        rel="apple-touch-icon"
        sizes="60x60"
        type="image/png"
        href="/icons/apple-icon-60x60.png"
      />
      <link
        rel="apple-touch-icon"
        sizes="72x72"
        type="image/png"
        href="/icons/apple-icon-72x72.png"
      />
      <link
        rel="apple-touch-icon"
        sizes="76x76"
        type="image/png"
        href="/icons/apple-icon-76x76.png"
      />
      <link
        rel="apple-touch-icon"
        sizes="114x114"
        type="image/png"
        href="/icons/apple-icon-114x114.png"
      />
      <link
        rel="apple-touch-icon"
        sizes="120x120"
        type="image/png"
        href="/icons/apple-icon-120x120.png"
      />
      <link
        rel="apple-touch-icon"
        sizes="144x144"
        type="image/png"
        href="/icons/apple-icon-144x144.png"
      />
      <link
        rel="apple-touch-icon"
        sizes="152x152"
        type="image/png"
        href="/icons/apple-icon-152x152.png"
      />
      <link
        rel="apple-touch-icon"
        sizes="180x180"
        type="image/png"
        href="/icons/apple-icon-180x180.png"
      />
      <link
        rel="icon"
        sizes="192x192"
        type="image/png"
        href="/icons/android-icon-192x192.png"
      />
      <link
        rel="icon"
        sizes="32x32"
        type="image/png"
        href="/icons/favicon-32x32.png"
      />
      <link
        rel="icon"
        sizes="96x96"
        type="image/png"
        href="/icons/favicon-96x96.png"
      />
      <link
        rel="icon"
        sizes="16x16"
        type="image/png"
        href="/icons/favicon-16x16.png"
      />
      <meta
        name="msapplication-TileImage"
        content="/icons/ms-icon-144x144.png"
      />
      <meta name="msapplication-TileColor" content="#ffffff" />
      <meta name="theme-color" content="#ffffff" />
    </>
  )
}
